[package]
name = "wavs"
description = "WAVS Node Server"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[features]
test-utils = []
dev = []
rerun = ["dep:wavs-rerun"]

[dependencies]
wavs-types = { workspace = true, features = ["full"] }
wavs-engine = { workspace = true }
utils = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
const-hex = { workspace = true }
thiserror = { workspace = true }
dashmap = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
tower = { workspace = true }
http-body-util = { workspace = true }
wildmatch = { workspace = true }
layer-climb = { workspace = true }
ctrlc = { workspace = true }
tempfile = { workspace = true }
futures = { workspace = true }
cosmwasm-std = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
alloy-contract = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-provider = { workspace = true }
alloy-sol-types = { workspace = true }
wasm-pkg-common = { workspace = true }
chrono = { workspace = true }
cron = { workspace = true }
bincode = { workspace = true }
axum-tracing-opentelemetry = { workspace = true }
opentelemetry = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
bimap = { workspace = true }
crossbeam = { workspace = true }
iri-string = { workspace = true }
tokio-tungstenite = { workspace = true }
slotmap = { workspace = true }
async-stream = "0.3.6"
rand = { workspace = true }
wavs-rerun = { workspace = true, optional = true }

[dev-dependencies]
criterion = { workspace = true }
wavs-benchmark-common = { workspace = true }
utils = { workspace = true, features = ["test-utils"] }
example-types = { workspace = true }
alloy-node-bindings = { workspace = true }


[[bench]]
name = "intervals"
harness = false
required-features = ["dev"]

[[bench]]
name = "engine_execute"
harness = false
required-features = ["dev"]

[[bench]]
name = "engine_system"
harness = false
required-features = ["dev"]

[[bench]]
name = "dev_triggers"
harness = false
required-features = ["dev"]
