[package]
name = "layer-tests"
description = "Layer end-to-end tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

# Only dev-dependencies since we only run this package via `cargo test`
[dev-dependencies]
wasm-pkg-common = { workspace = true }
wavs = { workspace = true }
wavs-types = { workspace = true, features = ["full"] }
utils = { workspace = true, features = ["test-utils"] }
wavs-cli = { workspace = true }
wavs-aggregator = { workspace = true }
cw-wavs-mock-api = { workspace = true }
cw-wavs-trigger-api = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
opentelemetry = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
const-hex = { workspace = true }
layer-climb = { workspace = true }
layer-climb-cli = { workspace = true }
tempfile = { workspace = true }
futures = { workspace = true }
cosmwasm-std = { workspace = true }
alloy-network = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true, features = ["anvil-node"] }
alloy-signer = { workspace = true }
alloy-contract = { workspace = true }
uuid = { workspace = true }
reqwest = { workspace = true }
dashmap = { workspace = true }
example-types = { workspace = true }
ordermap = { workspace = true }
regex = { workspace = true }
deadpool = { workspace = true }
derive-enum-all-values = { workspace = true }
rand = { workspace = true }
rand_core = "0.6"
bip39 = { workspace = true }
hypercore = { workspace = true }
hypercore-protocol = { workspace = true }
hyperswarm = { workspace = true }
futures-lite = { workspace = true }
async-std = "1"
