[default]
log_level = ["info", "wavs=debug"]

[layer-tests]
wavs_concurrency = true
middleware_concurrency = true
grouping = false
evm_middleware_type = "eigenlayer" # or "poa"
# Run all tests
# mode = "all"

# Run all ethereum tests (same can be done for cosmos, cross-chain, etc.)
# mode = "all_eth"

# Run a specific test
mode = { "isolated" = [{ evm = "multi_workflow" }] }

# Run a few specific tests
# mode = {"isolated" = [
#     {evm = "echo_data"},
#     {cosmos = "permissions"},
# ]}

# Load components from the registry
# registry = true

# Send tracing to Jaeger
# jaeger = "http://localhost:4317"

# Send metrics to Prometheus
# prometheus = "http://localhost:9090"
